Nm_erro = {
  "lang_jscr_dcml" : "Decimaler",
  "lang_jscr_decm" : "En tiendedel af et sekund",
  "lang_jscr_hour" : "Time",
  "lang_jscr_iday" : "Dag",
  "lang_jscr_intg" : "Integers og",
  "lang_jscr_ivcr" : "Ugyldigt Kredit Kort Nummer",
  "lang_jscr_ivdt" : "Ugyldig Data:",
  "lang_jscr_ivem" : "Ugyldig Email:",
  "lang_jscr_ivnb" : "Ugyldig integer",
  "lang_jscr_ivtm" : "Ugyldig tid:",
  "lang_jscr_ivv2" : "Ugyldig Data:",
  "lang_jscr_ivvl" : "Ugyldig decimal",
  "lang_jscr_maxm" : "Max",
  "lang_jscr_maxm_date" : "Max Dato",
  "lang_jscr_minm" : "Min",
  "lang_jscr_minm_date" : "Minimum Dato",
  "lang_jscr_mint" : "Minutter",
  "lang_jscr_mnth" : "Måned",
  "lang_jscr_msfr" : "Formen skal have et navn",
  "lang_jscr_mslg" : "login mangler;",
  "lang_jscr_msob" : "Dette form objekt skal have et navn",
  "lang_jscr_mxdg" : "Antal cifre oversteg forventede",
  "lang_jscr_mxvl" : "Max længde nået",
  "lang_jscr_nnum" : "Dette felt er numerisk",
  "lang_jscr_nvlf" : "Det negative tegn skal være på værdiens venstre",
  "lang_jscr_reqr" : "Krævede felt",
  "lang_jscr_secd" : "Sekunder",
  "lang_jscr_wfix" : "Vil du rette?"
}
